export const authConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  // LOGOUT: "USERS_LOGOUT",

  // GET_USER_REQUEST: "GET_USER_REQUEST",
  // GET_USER_SUCCESS: "GET_USER_SUCCESS",
  // GET_USER_FAILURE: "GET_USER_FAILURE",

  LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",

  AUTHENTICATE_USER_REQUEST: "AUTHENTICATE_USER_REQUEST",
  AUTHENTICATE_USER_REQUEST_SUCCESS: "AUTHENTICATE_USER_REQUEST_SUCCESS",
  AUTHENTICATE_USER_REQUEST_FAILURE: "AUTHENTICATE_USER_REQUEST_FAILURE"
};
