export const hotelConstants = {
  HOTEL_SET_WIDGET_VALUES: "HOTEL_SET_WIDGET_VALUES",

  HOTEL_GET_LISTINGS: "HOTEL_GET_LISTINGS",
  HOTEL_GET_LISTINGS_SUCCESS: "HOTEL_GET_LISTINGS_SUCCESS",
  HOTEL_GET_LISTINGS_FAILURE: "HOTEL_GET_LISTINGS_FAILURE"
};
